name: flutter_packages

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # BDS Colors package workflow.
  package_bds_colors:
    uses: ./.github/workflows/actions/flutter_package
    with:
      working_directory: "./packages/bds_colors/"

  # BDS Type package workflow.
  package_bds_type:
    uses: ./.github/workflows/actions/flutter_package
    with:
      working_directory: "./packages/bds_type/"
