name: packages

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.dart"
  push:
    branches:
      - main
    paths:
      - "**.dart"

jobs:
  # BDS Colors package workflow.
  package_bds_colors:
    uses: ./.github/workflows/flutter_package.yaml
    with:
      working_directory: "./packages/bds_colors/"

  # BDS Type package workflow.
  package_bds_type:
    uses: ./.github/workflows/flutter_package.yaml
    with:
      working_directory: "./packages/bds_type/"
